<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <OtherFlags>--nowarn:40 --tailcalls+ --optimize+</OtherFlags>
    <Tailcalls>True</Tailcalls>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="v1\Main.fs" />
    <Content Include="v0\serdes.b">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="v0\brief.b">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="v0\prelude.b">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="v0\tests.b">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Compile Include="v0\Structure.fs" />
    <Compile Include="v0\Serialization.fs" />
    <Compile Include="v0\Syntax.fs" />
    <Compile Include="v0\Print.fs" />
    <Compile Include="v0\Interpretation.fs" />
    <Compile Include="v0\Actor.fs" />
    <Compile Include="v0\Primitives.fs" />
    <Compile Include="v0\Tesla.fs" />
    <Compile Include="v0\Trigger.fs" />
    <Compile Include="v0\Remote.fs" />
    <Compile Include="v0\Main.fs" />
    <Content Include="v0\boot.i">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <None Include="Readme.md" />
    <None Include="Journal\Readme.md" />
    <None Include="Journal\DEC2020.md" />
    <None Include="Journal\OCT2021.md" />
    <None Include="Journal\NOV2021.md" />
    <None Include="Journal\DEC2021.md" />
    <None Include="Journal\JAN2021.md" />
    <None Include="Journal\JUL2023.md" />
    <None Include="Journal\JUL2024.md" />
    <None Include="Journal\Clojure.md" />
    <None Include="Vocabulary.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>

</Project>
